- .github/workflows/core-11.yml
- .github/workflows/core-12.yml
- .gitignore
- Build/Scripts/runTests.sh
This change introduces `Build/Scripts/runTests.sh` build
upon the latest state from the TYPO3 Core Team with only
a first set of basic tools. Will be extended with other
changes.
Most are stripped out, minor blocks are left commented
and will be adopted in one of the following changes.
Implemented suits:
* composer
* composerUpdate
* lintPhp
GitHub action for both core versions are added in the
same step with basic install and linting checks, which
will be extended when adding additional tools.
> [TASK] Introduce basc `Build/Scripts/runTests.sh`

- Build/Scripts/runTests.sh
- composer.json
The `COMPOSER_ROOT_VERSION` in `Build/Scripts/runTests.sh`
is set to suitable constraint.
```shell
composer config repositories.packages path "packages/*/*" \
do
composer require --dev --no-update \
"$( cat packages/fgtclb/${extension}/composer.json | jq -r .name )":"@dev"
done
```
> [TASK] Require all extensions as dev dependencies

- .github/workflows/core-12.yml
- packages/fgtclb/academic-projects/composer.json
TYPO3 v12 is allowed now for `EXT:academic_projects` to
align the extension with the other extensions abeit not
tested and verified yet.
Acts as preparation to test all extensions with v12 and
fix issues for extensions not having the constrains yet.
Additionally, the TYPO3 v12 workflow is adjusted to use
TYPO3 v12 correctly.
```shell
composer require --no-update \
-d packages/fgtclb/academic-projects \
'typo3/cms-backend':'^11.5 || ^12.4' \
'typo3/cms-core':'^11.5 || ^12.4' \
'typo3/cms-extbase':'^11.5 || ^12.4' \
'typo3/cms-fluid':'^11.5 || ^12.4' \
'typo3/cms-install':'^11.5 || ^12.4'
```
> [TASK] Allow TYPO3 v12 for `EXT:academic_projects`

- packages/fgtclb/academic-bite-jobs/composer.json
- packages/fgtclb/academic-contact4pages/composer.json
- packages/fgtclb/academic-jobs/composer.json
```shell
find packages/fgtclb \
do
composer config -d "packages/fgtclb/${extension}" \
sort-packages true \
&& composer require --no-update \
-d "packages/fgtclb/${extension}" \
"php":"^8.2 || ^8.3 || ^8.4" \
&& composer require --no-update \
-d "packages/fgtclb/${extension}" \
"php":"^8.1 || ^8.2 || ^8.3 || ^8.4"
done
```
> [TASK] Enable `sort-package` for all extensions

- .github/workflows/core-11.yml
- .github/workflows/core-12.yml
- .gitignore
- Build/Scripts/runTests.sh
- Build/php-cs-fixer/config.php
- Build/php-cs-fixer/header-comment.php
- composer.json
The `friendsofphp/php-cs-fixer` is a tool to ensure
a configurable PHP coding over all extensions with
a global configuration.
```shell
composer require --dev --no-update \
'friendsofphp/php-cs-fixer':'^3.57.1'
```
Changes applied with pull-request #10
> [TASK] Introduce php-cs-fixer for all extensions

- Build/php-unit/FunctionalTests.xml
- Build/php-unit/FunctionalTestsBootstrap.php
- Build/php-unit/UnitTests.xml
- Build/php-unit/UnitTestsBootstrap.php
This change uses the PHPUnit 10.* related templates
from `typo3/testing-framework` leaving 9.x files out
and adjusting the paths.
> [TASK] Configure and enable unit- and function tests

- Build/Scripts/runTests.sh
- Build/phpstan/Core11/phpstan-baseline.neon
- Build/phpstan/Core11/phpstan-constants.php
- Build/phpstan/Core11/phpstan.neon
- Build/phpstan/Core12/phpstan-baseline.neon
- Build/phpstan/Core12/phpstan-constants.php
- Build/phpstan/Core12/phpstan.neon
- composer.json
Static code analyzer is added to the repository
and configured with dual core configuration and
baseline support provided by the command wrapper
`Build/Scripts/runTests.sh`. The PHPStan level 8
is relativly high and currently reports some
errors for v11 where not all could be added to
the baseline and v12 crashes due to hard errors.
Based on that, baseline is kept empty for now to
investigate and fix most of the issues first and
enable ci pipeline when green state with a small
baseline is archieved.
It still make sense to add it so we can start to
investigate these issues.
```shell
composer require --no-update --dev \
'phpstan/phpstan':'^1.12.21' \
'phpstan/phpdoc-parser':'^1.29.0' \
'phpstan/phpstan-phpunit':'^1.4.0' \
'bnf/phpstan-psr-container':'^1.0.1' \ …
```
> [TASK] Add static code analyzer `phpstan`

- .github/workflows/core-11.yml
- .github/workflows/core-12.yml
- Build/Scripts/runTests.sh
This change enables the unit and randomized unit
test execution for all packages within provided
`Build/Scripts/runTests.sh` dispatcher.
The PHPUnit command used to execute the unit tests
defines exclude group for currently executed TYPO3
core version `not-core-XY` to allow disabling test
or testcases for a specific TYPO3 version.
Unit testing is now also enabled within the GitHub
action workflow definitions.
> [TASK] Add unit-testing for all packages

- composer.json
This change adds the packages test namespace definition
directly to the root composer.json as `autoload-dev` to
have test related classes beeing autoloaded during test
execution.
> [TASK] Add package test namespaces to root composer.json

- composer.json
With a previous change extension test folders has been
added as `autoload-dev` to the root package, and sadly
for two extension the casing for the namespace weren't
correct. Use correct casing now.
```shell
cat <<< $(jq --indent 4 'del(."autoload-dev"."psr-4"."FGTCLB\\AcademicPersons\\Tests\\")' composer.json) > composer.json.1 \
&& cat <<< $(jq --indent 4 'del(."autoload-dev"."psr-4"."FGTCLB\\Fgtclb\\Tests\\")' composer.json.1) > composer.json.2 \
&& cat <<< $(jq --indent 4 '."autoload-dev"."psr-4" += {"Fgtclb\\AcademicPersons\\Tests\\": "packages/academic-persons/Tests"}' composer.json.2) > composer.json.3 \
&& cat <<< $(jq --indent 4 '."autoload-dev"."psr-4" += {"Fgtclb\\AcademicPersonsEdit\\Tests\\": "packages/academic-persons-edit/Tests"}' composer.json.3) > …
```
> [TASK] Use correct casing for test autoload namespaces

- composer.json
It is a common requirement to add fixture extensions to
functional tests to test against multiple differentiating
setups, which requires that the fixture extension composer
namespaces are added to the root composer.json.
That can be a maintenance burden and a composer plugin has
been created to tackle this effort, which is still in kind
of a development phase but already usable for the subset
required in this mono repository and is added now to act
as further preparation to enable functional testing for all
extensions.
```shell
mv composer.json composer.json.1 \
&& cat <<< $(jq --indent 4 '.extra."sbuerk/fixture-packages" += ["packages/*/Tests/Functional/Fixtures/Extensions/*"]' composer.json.1) > composer.json \
&& composer config allow-plugins.sbuerk/fixture-packages …
```
> [TASK] Automatically register test fixture extensions

- composer.json
Recently test folder autoload namespaces has been added to
the root `composer.json`, and already tried to fix.
It's a bad idea to work with lack of sleep, which increases
errors and happened here.
This change registers the autoload namespaces now with the
correct relative folder. Hopefully this can be simplified
with the `sbuerk/fixture-package` composer plugin in the
future also for mono repo packages.
```shell
composer config --unset autoload-dev \
&& composer config --unset extra."sbuerk/fixture-packages" \
&& mv composer.json composer.json.orig \
&& cat <<< $(
jq --indent 4 '.extra."sbuerk/fixture-packages" += ["packages/*/*/Tests/Functional/Fixtures/Extensions/*"]' composer.json.orig | \
jq --indent 4 '."autoload-dev"."psr-4" += {"FGTCLB\\AcademicBiteJobs\\Tests\\": …
```
> [TASK] Ensure to use correct path for extension test namespaces

- composer.json
- packages/fgtclb/academic-persons/composer.json
The `fgtclb/academic-persons` functional tests requires
to have `georgringer/numbered-pagination` available, so
it can be loaded as extension in test instances.
This change adds this dependency now to the `composer.json`
of the mono repository and removes it from the package.
```shell
composer remove --dev --no-update \
-d packages/fgtclb/academic-persons \
'georgringer/numbered-pagination' \
&& COMPOSER_ROOT_VERSION='1.2.x-dev' composer require \
--dev 'georgringer/numbered-pagination':'^1.0'
```
> [TASK] Add `georgringer/numbered-pagination` dev dependency

- packages/fgtclb/academic-bite-jobs/composer.json
- packages/fgtclb/academic-jobs/composer.json
- packages/fgtclb/academic-partners/composer.json
- packages/fgtclb/academic-persons-edit/composer.json
- packages/fgtclb/academic-persons-sync/composer.json
- packages/fgtclb/academic-persons/composer.json
- packages/fgtclb/academic-programs/composer.json
- packages/fgtclb/academic-projects/composer.json
- packages/fgtclb/typo3-category-types/composer.json
The extension packages (`packages/*/*`)  are splitted
and considerable readonly. Development happens within
the mono repository now and development dependencies,
tooling and tooling configuration can be removed from
each individual package and will be handled on global
level.
```shell
COMPOSER_BIN="$( which composer )" \
do
${COMPOSER_BIN} remove --dev --no-update \
-d "packages/fgtclb/${extension}" \
'helhum/typo3-console' \
'saschaegerer/phpstan-typo3' \
'friendsofphp/php-cs-fixer' \
'bk2k/bootstrap-package' \
&& ${COMPOSER_BIN} config -d "packages/fgtclb/${extension}" \
--unset scripts
done
```
> [TASK] Remove development dependencies from packages

- packages-dev/monorepo-shared/composer.json
- packages/fgtclb/academic-partners/composer.json
- packages/fgtclb/academic-partners/ext_localconf.php
`academic-partners` provides a `EXT:scheduler` task
to automatically geocode entities used to display
in a map.
This change adds `EXT:scheduler` as suggestion to
the academic extensions and as dependency to the
mono repository to test (late) the functionality.
```shell
COMPOSER_BIN="$( which composer )" \
&& ${COMPOSER_BIN} config \
-d packages/fgtclb/academic-partners \
suggest."typo3/cms-scheduler" \
"Install EXT:scheduler for the automatic geocoding" \
&& ${COMPOSER_BIN} config \
-d packages-dev/monorepo-shared \
sort-packages true \
&& ${COMPOSER_BIN} require --no-update \
-d packages-dev/monorepo-shared \
'typo3/cms-scheduler':'^11.5 || ^12.4'
```
> [TASK] Adding `typo3/cms-scheduler` dependency

- README.md
- packages/fgtclb/academic-bite-jobs/README.md
- packages/fgtclb/academic-contact4pages/README.md
- packages/fgtclb/academic-jobs/README.md
- packages/fgtclb/academic-partners/README.md
- packages/fgtclb/academic-persons-edit/README.md
- packages/fgtclb/academic-persons-sync/README.md
- packages/fgtclb/academic-persons/README.md
- packages/fgtclb/academic-programs/README.md
- packages/fgtclb/academic-projects/README.md
- packages/fgtclb/typo3-category-types/README.md
This change fills the mono repository root `README.md`
file with first information and also hops through all
of the extension `README.md` files to:
* Align the structure of the `README.md` to a shared
build up.
* Add compatibility information.
* Add TYPO3 knwon extension link box at the top.
* Align installation intstructions towards the same
way in all extensions.
* Ensure missing fgctclb credits in the files.
> [DOCS] Streamline root and extension `README.md` files

- packages/fgtclb/academic-bite-jobs/composer.json
- packages/fgtclb/academic-jobs/composer.json
- packages/fgtclb/academic-partners/composer.json
- packages/fgtclb/academic-persons-edit/composer.json
- packages/fgtclb/academic-persons-sync/composer.json
- packages/fgtclb/academic-persons/composer.json
- packages/fgtclb/academic-programs/composer.json
- packages/fgtclb/academic-projects/composer.json
- packages/fgtclb/typo3-category-types/composer.json
Extensions are splitted and soley developed within
this mono repository, which means that there is no
need to maintain development dependencies in each
extension `composer.json`. Let's clean that up.
```shell
COMPOSER_BIN="$( which composer2-81 )" \
do
${COMPOSER_BIN} config --unset require-dev \
-d "packages/fgtclb/${extension}"
done
```
> [TASK] Remove dev-dependencies from extensions

- composer.json
- packages/fgtclb/academic-bite-jobs/composer.json
- packages/fgtclb/academic-contact4pages/composer.json
- packages/fgtclb/academic-jobs/composer.json
- packages/fgtclb/academic-partners/composer.json
- packages/fgtclb/academic-persons-edit/composer.json
- packages/fgtclb/academic-persons-sync/composer.json
- packages/fgtclb/academic-persons/composer.json
- packages/fgtclb/academic-programs/composer.json
- packages/fgtclb/academic-projects/composer.json
- packages/fgtclb/typo3-category-types/composer.json
```shell
COMPOSER_BIN="$( which composer2-81 )" \
do
${COMPOSER_BIN} config -d "packages/fgtclb/${extension}" \
--unset extra.branch-alias
${COMPOSER_BIN} config -d "packages/fgtclb/${extension}" \
extra.branch-alias."dev-main" "1.2.x-dev"
done \
&& ( ${COMPOSER_BIN} config --unset extra.branch-alias | true ) \
&& ( ${COMPOSER_BIN} config extra.branch-alias."dev-main" "1.2.x-dev" )
> [TASK] Ensure branch alias settings for split extensions

- packages/fgtclb/academic-bite-jobs/composer.json
- packages/fgtclb/academic-contact4pages/composer.json
- packages/fgtclb/academic-jobs/composer.json
- packages/fgtclb/academic-projects/composer.json
```shell
COMPOSER_BIN="$( which composer2-81 )" \
do
cat <<< $(
jq --indent 4 '."license" = "GPL-2.0-or-later"' "packages/fgtclb/${extension}/composer.json"
) > "packages/fgtclb/${extension}/composer.json"
done \
&& cat <<< $(
jq --indent 4 '."license" = "GPL-2.0-or-later"' "packages-dev/monorepo-shared/composer.json"
) > "packages-dev/monorepo-shared/composer.json" \
&& cat <<< $(
jq --indent 4 '."license" = "GPL-2.0-or-later"' "composer.json"
) > "composer.json"
```
> [TASK] Normalize `license` field in `composer.json` files

- composer.json
This change configure the mono repository root `composer.json`
to prefer TYPO3 system extension installed from source instead
if dist packages for following reasons:
* It elimates to maintain a own `SiteBasedTestTrait` as we can
use the TYPO3 Core Team maintained version instead and also
mitigates to deal with multi-core version support.
* We have also the development resources from the TYPO3 core
in the system, except stuff only included within the TYPO3
core mono repository (sadly). At least we have easy access
to TYPO3 core tests to look things up as inspiration. That
reduces possible excuses **not** to implement tests during
on-going work literally invalid.
Note that we still pull only released versions of the TYPO3
system extension, but without stripped resources like the
test folder …
> [TASK] Prefer installing selected system extensions from source

- .github/workflows/core-13.yml
- Build/phpunit/FunctionalTests.xml
- Build/phpunit/FunctionalTestsBootstrap.php
- Build/phpunit/UnitTests.xml
- Build/phpunit/UnitTestsBootstrap.php
With the recent change to move towards `2.x.x` and changing
the supported TYPO3 version to `v12/v13` the testing related
dependency `typo3/testing-framework` has been updated.
This change aligns now the mono repository configuration to
the provided examples within the package, removing obsolete
stuff from the configuration.
Functional tests are now enabled in the GitHub workflow for
TYPO3 v13.
> [TASK] Update `typo3/testing-framework` and `phpunit` setup

- packages/fgtclb/academic-jobs/Configuration/Flexforms/Plugin_NewJobForm.xml
During consolidation of the acadamic extensions into
a mono repository and pulling as much in as possible,
editing one plugin xml introduced invalid characters
and leading to invalid xml.
This is now fixed with this change by removing the
obsolete characters again.
> [BUGFIX] Ensure valid xml-format for plugin flexform

- README.md
This change adds a small table to the main branch
`README.md` to hold a small overrview of verified
state accross extension version and TYPO3 version.
> [DOCS] Add little extension/version/support state

- packages/fgtclb/typo3-category-types/composer.json
The autoload configuration was errornous removed from composer configuration.
> [TASK] Add composer autoload configuration for `fgtclb/category-types`

- composer.json
[TASK] Upgrade `sbuerk/fixture-packages`
A new versiono `sbuerk/fixture-packages` has been released,
including the fixed static path for fetching the fixture
packages within the class to adopt fixture packages for the
`typo3/testing-framework` functional tests and the ability
to select `autoload` and/or `autoload-dev` to be adopted
per path configuration.
This change now updates this package, removes the workaround
using PHP reflection API in the `FunctionalTestsBootstrap`,
removes the manual test namespace registration for our own
academic mono-repository packages. Sadly, TYPO3 does not
declare the test namespaces within the system extension
`composer.json` yet and the automatic adoption does not
work using this composer plugin. We will see what the
future brings.
For the future, this …
> [TASK] Upgrade `sbuerk/fixture-packages`

- Build/phpunit/FunctionalTestsBootstrap.php
- Build/phpunit/UnitTestsBootstrap.php
- packages/fgtclb/academic-persons/Classes/Controller/ProfileController.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/Dto/ProfileDemand.php
- packages/fgtclb/academic-persons/Classes/Domain/Repository/ProfileRepository.php
- packages/fgtclb/academic-persons/Configuration/FlexForms/Core11/List.xml
- packages/fgtclb/academic-persons/Configuration/FlexForms/Core11/SelectedContracts.xml
- packages/fgtclb/academic-persons/Configuration/FlexForms/Core11/SelectedProfiles.xml
- packages/fgtclb/academic-persons/Configuration/FlexForms/List.xml
- packages/fgtclb/academic-persons/Configuration/FlexForms/SelectedContracts.xml
- packages/fgtclb/academic-persons/Configuration/FlexForms/SelectedProfiles.xml
- packages/fgtclb/academic-persons/Resources/Private/Language/de.locallang_be.xlf
- packages/fgtclb/academic-persons/Resources/Private/Language/locallang_be.xlf
This pull-requests introduces a additional view mode selection,
which allows to define the presentation mode per plugin usage.
That means, switching between list or grid view.
Further, organizational units and function types are selectable
per plugin placement acting as filter for the frontend retrivale
of the dataset.
> [FEATURE] Introduce view mode selection and additional backend filter

- packages/fgtclb/academic-projects/Configuration/TCA/Overrides/pages.php
Due to the fields database registration in ext_tables.sql the budget field is set to be NULL by default. Whenever a page is copied, this field is processed by the DataHandler to set a correct value in the database. When trying to resolve the value the DataHandler crashes because it can't preg_replace on NULL (see https://github.com/TYPO3/typo3/blob/45a64eb0329655690ec087fceb0bf60c250e60ff/typo3/sysext/core/Classes/DataHandling/DataHandler.php#L1564).
Therefore either the DEFAULT value in ext_tables.sql needs to be changed to 0 or the field is "nullable" which converts the NULL value to an empty string. The number field type probably cannot be NULL by default, which is why the issue is occurring. It was decided to add the nullable checkbox to the field to still be able to differentiate …
> [TASK] Allow budget field to be nullable

- packages/fgtclb/academic-contact4pages/Classes/DataProcessing/ContactsProcessor.php
- packages/fgtclb/academic-contact4pages/Classes/Upgrades/PluginUpgradeWizard.php
This pull-requests provides the missing TYPO3 UpgradeWizard
for the renamed `EXT:academic_contacts4pages` plugin completed
with pull-request #60 .
Readding missing context data full-filled by related `DataProcessor`
is done as a side-change, masked as TASK albeit fixing a bug.
> [TASK] Add upgrade wizard for renamed plugin of `contacts4pages`

- .github/workflows/core-13.yml
It is essential to execute the `cgl` check based on
the `php-cs-fixer` in dry-run mode, controlled with
the `-n` flag of `Build/Scripts/runTests.sh` to get
failing error code when cgl fixes should be applied.
This has been missed, and for TYPO3 v12 already added
in recent change. Let's make the same change for TYPO3
v13 to have a double check in place.
> [TASK] Use cgl check mode with TYPO3 v13

- Build/phpstan/Core13/phpstan-baseline.neon
- packages/fgtclb/academic-contact4pages/Classes/Controller/ContactsController.php
The `EXT:academic_contacts4pages` extension still contains some
TYPO3 v11 compatibility code branches, which are no longer needed.
This change removes the old way to retrieve the content object by
dropping the conditional TYPO3 v11 branch from the controller. [1]
Makes one PHPStan error ignorePattern obsolete for TYPO3 v13 and
is removed in the same step.
```shell
Build/Scripts/runTests.sh -t 13 -p 8.2 -s composerUpdate \
&& Build/Scripts/runTests.sh -t 13 -p 8.2 -s phpstanGenerateBaseline
```
[1] https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4/Deprecation-100662-ConfigurationManager-getContentObject.html
> [TASK] Remove TYPO3 v11 content object compat in `contacts4pages`

- packages/fgtclb/academic-contact4pages/Configuration/TCA/tx_academiccontacts4pages_domain_model_contact.php
- packages/fgtclb/academic-contact4pages/Configuration/TCA/tx_academiccontacts4pages_domain_model_role.php
The `cruser_id` setting and field for TCA managed tables
has been removed breaking in TYPO3 v12.0 and setting TCA
ctrl section option leads to automatic TCA migration and
emits `E_USER_DEPRECATED` notices. [1]
No need to keep it in anyway, remove it.
[1] https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98024-TCA-option-cruserid-removed.html
> [TASK] Remove vanished `cruser_id` from TCA

- Build/phpstan/Core12/phpstan-baseline.neon
- Build/phpstan/Core13/phpstan-baseline.neon
- packages/fgtclb/academic-jobs/Classes/Controller/JobController.php
TYPO3 v11 support has been dropped, remove some traces of
compatibility code not needed anymore and clean the house.
This change also allows us to get rid of a couple of phpstan
error ignore patterns in baseline for both TYPO3 versions.
```shell
Build/Scripts/runTests.sh -t 12 -p 8.1 -s composerUpdate \
; Build/Scripts/runTests.sh -t 12 -p 8.1 -s cgl \
; Build/Scripts/runTests.sh -t 12 -p 8.1 -s phpstanGenerateBaseline \
; Build/Scripts/runTests.sh -t 13 -p 8.2 -s composerUpdate \
; Build/Scripts/runTests.sh -t 13 -p 8.2 -s phpstanGenerateBaseline \
; Build/Scripts/runTests.sh -t 12 -p 8.1 -s composerUpdate
```
> [!!!][TASK] Remove TYPO3 v11 related code from `academic-jobs`

- packages/fgtclb/academic-partners/ext_tables.php
- packages/fgtclb/academic-programs/ext_tables.php
- packages/fgtclb/academic-projects/ext_tables.php
TYPO3 v12.0 removed `$GLOBALS['PAGES_TYPES']` [1] in
favour of the new `PageDoktypeRegistry` [2] class.
[1] https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98487-GLOBALSPAGES_TYPESRemoved.html
[2] https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/PageTypes/CreateNewPageType.html
> [TASK] Replace removed `$GLOBALS['PAGES_TYPES']`

- packages/fgtclb/academic-contact4pages/Configuration/TCA/Overrides/pages.php
- packages/fgtclb/academic-contact4pages/Configuration/TCA/Overrides/tx_academicpersons_domain_model_contract.php
TYPO3 v12 removed some FAL related behaviour TCA settings
for TCA type=inline, providing automatic TCA migration and
emitting `E_USER_DEPRECATED` errors.
Since TYPO3 v12 is the minimal supported TYPO3 version,
related TCA configuration are now dropped aggordingly
to the TYPO3 changelog entry [1].
[1] https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98479-RemovedFileReferenceRelatedFunctionality.html
> [TASK] Mitigate removed FAL related behaviour for `TCA type=inline`

- Build/phpstan/Core12/phpstan-baseline.neon
- Build/phpstan/Core13/phpstan-baseline.neon
- packages/fgtclb/academic-bite-jobs/Classes/Controller/BiteJobsController.php
- packages/fgtclb/academic-bite-jobs/Classes/Services/BiteJobsService.php
- packages/fgtclb/academic-partners/Classes/Controller/PartnerController.php
- packages/fgtclb/academic-persons/Classes/Controller/ProfileController.php
- packages/fgtclb/academic-programs/Classes/Controller/DetailsController.php
- packages/fgtclb/academic-programs/Classes/Controller/ProgramController.php
- packages/fgtclb/academic-projects/Classes/Controller/ProjectController.php
During the upgrade towards new TYPO3 version support, the
retrieval of the current object renderer has been aligned
multiple times and capsulated into a dedicate method. The
name is picked up by the extension leading to fals-positives,
which may be disturbing to consumers.
This change replaces these places by using a method name
not picked up by the extension scanner and allows us to
remove more PHPStan error ignore patterns from the baseline.
```shell
Build/Scripts/runTests.sh -t 12 -p 8.1 -s composerUpdate \
; Build/Scripts/runTests.sh -t 12 -p 8.1 -s cgl \
; Build/Scripts/runTests.sh -t 12 -p 8.1 -s phpstanGenerateBaseline \
; Build/Scripts/runTests.sh -t 13 -p 8.2 -s composerUpdate \
; Build/Scripts/runTests.sh -t 13 -p 8.2 -s phpstanGenerateBaseline \
; …
```
> [TASK] Mitigate extension scanner matches in `academic-projects`

- packages/fgtclb/academic-persons/Configuration/TCA/tx_academicpersons_domain_model_contract.php
- packages/fgtclb/academic-persons/Resources/Private/Language/locallang_tca.xlf
`EXT:academic_persons` uses now correct localization    
key for contracts column TCA definition, and adds an
missing key for profile field in another TCA config.
> [BUGFIX] Use suiting translation keys in TCA   

- packages/fgtclb/academic-persons/Configuration/TCA/tx_academicpersons_domain_model_contract.php
- packages/fgtclb/academic-persons/Resources/Private/Language/locallang_tca.xlf
`EXT:academic_persons` uses now correct localization
key for contracts column TCA definition, and adds an
missing key for profile field in another TCA config.
> [BUGFIX] Use suiting translation keys in TCA

- .gitignore
- ddev-instances/core-12/.ddev/config.yaml
- ddev-instances/core-12/.ddev/docker-compose.mounts.yaml
- ddev-instances/core-12/composer.json
- ddev-instances/core-13/.ddev/config.yaml
- ddev-instances/core-13/.ddev/docker-compose.mounts.yaml
- ddev-instances/core-13/composer.json
- ddev-instances/packages
- ddev-instances/packages-dev
This change aims to introduce a first ddev based local
development setup in a raw first form, extended on the
journey and enhanced over time. Still, adding this now
allows to at least start these instances and having a
development and playground albeit not provisining them
with a workable dataset (yet!). And not having them to
be destroyed before working on main or pull-requests
are a time safer already. And, it can be used to get
first user experiences which may adjust further plans
early.
Instance composer.json files are clones of the root
`composer.json file`, with adjusted path repository
path configuration, removed `sbuerk/fixture-package`
and additionally `typo3/minimal` with respective
version of TYPO3 for the instance.
For both instances, additional `.ddev` web container
docker …
> [TASK] Introduce ddev based local development instances

- Build/phpstan/Core12/phpstan-baseline.neon
- Build/phpstan/Core13/phpstan-baseline.neon
- packages/fgtclb/academic-contact4pages/Classes/Domain/Repository/ContactRepository.php
- packages/fgtclb/academic-contact4pages/Configuration/TCA/Overrides/pages.php
- packages/fgtclb/academic-contact4pages/Configuration/TCA/Overrides/tx_academicpersons_domain_model_contract.php
- packages/fgtclb/academic-contact4pages/Configuration/TCA/tx_academiccontacts4pages_domain_model_contact.php
All contact records are edited in the default language only, therefore
the loading of the contact records might not be very intuitive. The
data handler enforces a translation of inline records for which "l10n_mode"
is set to "exclude".
To keep this record in sync with the record in the default language, all
relevant contact fields must have set "l10n_mode" to "exclude", too. We
need an additional "page" field to store the relation between the page
and the contact records in the respective language.
Finally, the handling in the extbase repository adds the missing piece
to configure extbase towards proper language overlay handling combined  
with constraints based on backend selected record ids, which are always
in default language to mitigate side effects recieving records from the …
> [BUGFIX] Adopt required contacts handling changes for TYPO3 requirements (`contacts4pages`)

- packages/fgtclb/academic-projects/Configuration/Services.yaml
- packages/fgtclb/academic-projects/Configuration/TypoScript/Content/ContentLoad.typoscript
- packages/fgtclb/academic-projects/Configuration/TypoScript/setup.typoscript
- packages/fgtclb/academic-projects/Resources/Private/Pages/AcademicProject.html
- packages/fgtclb/academic-projects/Resources/Private/Partials/Categories.html
This pull-request ensures that `EXT:academic_projects`
data processor works by using the correct namespace in
the `Services.yaml`, which has not been adjusted after
copy & pasting from another extension.
Minor tasks are done as dedicated changes around this,
mainly targeting deprecated stuff.
* Use correct service namespace in `Services.yaml`.
* Remove deprecated skipDefaultArguments setting
in TS setup.
* Add TS configuration to load page content for
default page template.
* Update project page template to display all
project related data:
* Add output for title, images, page properties
and content elements.
* Add categories partial to output assigned system
catgeories in the page template.
> [BUGFIX] Use correct service namespace in `Services.yaml`

- packages/fgtclb/academic-partners/Resources/Private/Backend/Partials/PageLayout/Doktype40.html
- packages/fgtclb/academic-programs/Resources/Private/Backend/Partials/PageLayout/Doktype20.html
- packages/fgtclb/academic-projects/Resources/Private/Backend/Partials/PageLayout/Doktype30.html
- packages/fgtclb/typo3-category-types/Classes/Domain/Model/Category.php
- packages/fgtclb/typo3-category-types/Classes/Domain/Repository/CategoryRepository.php
- packages/fgtclb/typo3-category-types/Classes/ViewHelpers/Be/CategoryViewHelper.php
Hidden system categories assigned to consuming records are not
display in the backend and are considerable a `UX` fail within
the backend context and does not follow known TYPO3 behaviour
related to backend system category handling.
To align the behaviour towards known handling in backend context,
this change ...
* Add a `hidden` property to category model to make it available
in backend templates.
* Remove the hidden restriction for loading categories in backend
even if the parent page or the category is hidden.
* Display hidden categories in the backend with hidden icon to
show the hidden status.
> [BUGFIX] Display assigned hidden system categories in backend views

- packages/fgtclb/academic-partners/Classes/Factory/DemandFactory.php
- packages/fgtclb/academic-partners/Configuration/TCA/Overrides/tt_content.php
- packages/fgtclb/academic-programs/Classes/Factory/DemandFactory.php
- packages/fgtclb/academic-programs/Configuration/TCA/Overrides/tt_content.php
- packages/fgtclb/academic-projects/Classes/Factory/DemandFactory.php
- packages/fgtclb/academic-projects/Configuration/TCA/Overrides/tt_content.php
* Respect that database tt_content field `pages` is nullable 
by streamlining the check if explodable page ids are set
or not while setting the demand setting in `DemandFactory`.
* Add `pages` field in TCA showitem definition for the plugins
again to allow selecting pages for them.
> [BUGFIX] Restore selected pages plugin setting handling

- packages/fgtclb/academic-partners/Classes/Controller/PartnerController.php
- packages/fgtclb/academic-partners/Classes/Domain/Model/Partner.php
- packages/fgtclb/academic-partners/Classes/ViewHelpers/Form/SortingSelectViewHelper.php
- packages/fgtclb/academic-partners/Configuration/TCA/Overrides/pages.php
- packages/fgtclb/academic-partners/Configuration/TCA/Overrides/tt_content.php
- packages/fgtclb/academic-partners/Configuration/TsConfig/BackendLayouts/Partner.tsconfig
- packages/fgtclb/academic-partners/Configuration/TsConfig/Wizards/NewContentElement.tsconfig
- packages/fgtclb/academic-partners/Resources/Private/Language/de.locallang.xlf
- packages/fgtclb/academic-partners/Resources/Private/Language/de.locallang_be.xlf
- packages/fgtclb/academic-partners/Resources/Private/Pages/AcademicPartners.html
- packages/fgtclb/academic-partners/Resources/Private/Partials/Categories.html
- packages/fgtclb/academic-partners/Resources/Private/Partials/Partner/DemandCategories.html
- packages/fgtclb/academic-partners/Resources/Private/Partials/Partner/DemandSorting.html
- packages/fgtclb/academic-partners/Resources/Private/Partials/Partner/Items.html
- packages/fgtclb/academic-partners/Resources/Private/Partials/Partner/SingleItem.html
- packages/fgtclb/academic-partners/Resources/Private/Templates/Partner/List.html
- packages/fgtclb/academic-partners/Resources/Private/Templates/Partner/Map.html
- packages/fgtclb/academic-partners/ext_localconf.php
* Move map view to new plugin to supply a basic
and stable JS independent list of projects.
* Add templates and partials for filtering and
sorting in list and map view.
* Add german translation and optimize translation
files.
* Optimize markup of templates and code styling.
* Add `SortingSelectViewHelper` to render select
field markup within a template based on passed
options array or falling back to the available
`SortingOptions::getConstants()`.
> [TASK] Optimize templating for `academic_projects`

- packages/fgtclb/academic-partners/Configuration/TCA/Overrides/pages.php
- packages/fgtclb/academic-partners/Configuration/TCA/tx_academicpartners_domain_model_partnership.php
- packages/fgtclb/academic-partners/Configuration/TCA/tx_academicpartners_domain_model_role.php
- packages/fgtclb/academic-partners/Resources/Private/Language/de.locallang_be.xlf
- packages/fgtclb/academic-partners/Resources/Private/Language/locallang_be.xlf
While implementing partnerships and integrating them into the page configuration the language keys for the backend fields were searched for inside the locallang_db file. This file does not exist but the labels were added to the locallang_be file. Therefore the target files were adjusted.
> [TASK] Fix backend labels of partnerships

- packages/fgtclb/typo3-category-types/Classes/Loader/CategoryTypeLoader.php
* Add a new configuration option `remove` to remove category
types defined earlier in the configuartion chain.
* Add a new configuration option `useExisting` to override
settings like title or icon for category types defined
earlier in the configuartion chain.
> [FEATURE] Introduce `remove` and `useExisting` category type options

- packages/fgtclb/typo3-category-types/Configuration/TCA/Overrides/sys_category.php
Fix the missing icon for the default category type introduced by
`category_types` by adding the identifier for the default category
type to the list of `typeicon_classes`. Therefore the order of
variable initializations has been optimized.
> [BUGFIX] Add missing icon for default category type

- Build/phpstan/Core12/phpstan-baseline.neon
- Build/phpstan/Core13/phpstan-baseline.neon
- packages/fgtclb/academic-persons-edit/Classes/Controller/ProfileController.php
- packages/fgtclb/academic-persons-edit/Classes/Domain/Repository/AddressRepository.php
- packages/fgtclb/academic-persons-edit/Classes/Property/TypeConverter/ProfileImageUploadConverter.php
- packages/fgtclb/academic-persons-edit/Configuration/TCA/Overrides/sys_template.php
- packages/fgtclb/academic-persons-edit/Resources/Private/Language/de.locallang.xlf
- packages/fgtclb/academic-persons-edit/Resources/Private/Language/locallang.xlf
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/ProfileEdit/Contract/Addresses.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/ProfileEdit/Contract/EmailAddresses.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/ProfileEdit/Contract/PhoneNumbers.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/ProfileEdit/ProfileContract.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/ProfileEdit/ProfileData.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/ProfileEdit/ProfileImage.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/ProfileEdit/ProfileInformation/Cooperation.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Templates/Profile/ShowProfileEditingForm.html
- packages/fgtclb/academic-persons/Classes/Domain/Model/Contract.php
- packages/fgtclb/academic-persons/Configuration/TCA/tx_academicpersons_domain_model_profile.php
- packages/fgtclb/academic-persons/ext_tables.sql
* Change image property mapping and upload from raw `array` access to `TYPO3\CMS\Core\Http\UploadedFile` handling introduced with TYPO3 v12. See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97214-UseUploadedFileObjectsInsteadOf_FILES.html#breaking-97214
* Use enums for severities introduced with TYPO3 v12. See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-97787-EnumForSeveritiesIntroduced.html
* Make location in contracts nullable to avoid error when no location was seleceted in the frontend form.
* Add missing editing fields for personal data (e.g. first and last name) to templates and partials.
* Optimize templates and partials for better readability.
> [TASK] Update `academic_persons_edit` for v12/v13

- packages/fgtclb/academic-projects/Classes/Upgrades/PluginUpgradeWizard.php
The `EXT:academic_projects` upgrade wizard for `list_type` to `CType`
migration does not use correct value quoting.
To mitigate that, named placeholder are now used for the `UPDATE`
statement creation and also sets `list_type` to an empty string
now to complete the migration.
> [BUGFIX] Use named placeholder in `EXT:academic_projects` upgrade wizard

- packages/fgtclb/academic-projects/Classes/Upgrades/PluginUpgradeWizard.php
`EXT:academic_projects` upgrade wizard has been modified
recently to use proper named placeholder and clearing
the `list_type` added along the way - with an typo in the
column name. This is now corrected.
> [BUGFIX] Use correct column name in UpgradeWizard update query

- packages/fgtclb/academic-bite-jobs/Documentation/guides.xml
- packages/fgtclb/academic-jobs/Documentation/guides.xml
- packages/fgtclb/academic-persons-edit/Documentation/guides.xml
- packages/fgtclb/academic-persons-sync/Documentation/guides.xml
- packages/fgtclb/academic-persons/Documentation/guides.xml
- packages/fgtclb/academic-projects/Documentation/guides.xml
- packages/fgtclb/typo3-category-types/Documentation/guides.xml
This change migrates existing extension documentation
to new php based renderer using the provided migration
command.
Used command(s) for each extension:
```shell
docker run --rm --pull always -v $(pwd):/project \
-it ghcr.io/typo3-documentation/render-guides:latest \
migrate Documentation
```
[1] https://docs.typo3.org/other/t3docs/render-guides/main/en-us/Migration/Index.html
> [DOCS] Migrate documentation to php-based rendering

- packages/fgtclb/academic-contact4pages/Classes/Domain/Model/Contact.php
- packages/fgtclb/academic-contact4pages/Classes/Domain/Model/Role.php
- packages/fgtclb/academic-jobs/Classes/Domain/Model/Contact.php
- packages/fgtclb/academic-jobs/Classes/Domain/Model/Job.php
- packages/fgtclb/academic-partners/Classes/Domain/Model/Dto/PartnerDemand.php
- packages/fgtclb/academic-partners/Classes/Domain/Model/Partner.php
- packages/fgtclb/academic-partners/Classes/Domain/Model/Partnership.php
- packages/fgtclb/academic-partners/Classes/Domain/Model/Role.php
- packages/fgtclb/academic-persons-edit/Classes/Domain/Model/Address.php
- packages/fgtclb/academic-persons-edit/Classes/Domain/Model/FrontendUser.php
- packages/fgtclb/academic-persons-edit/Classes/Domain/Model/Location.php
- packages/fgtclb/academic-persons-edit/Classes/Domain/Model/Profile.php
- packages/fgtclb/academic-persons-sync/Classes/Domain/Model/FrontendUser.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/Address.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/Contract.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/Email.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/FunctionType.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/Location.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/OrganisationalUnit.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/PhoneNumber.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/Profile.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/ProfileInformation.php
- packages/fgtclb/academic-programs/Classes/Domain/Model/Dto/ProgramDemand.php
- packages/fgtclb/academic-programs/Classes/Domain/Model/Program.php
- packages/fgtclb/academic-programs/Classes/Domain/Model/ProgramData.php
- packages/fgtclb/academic-projects/Classes/Domain/Model/Dto/ProjectDemand.php
- packages/fgtclb/academic-projects/Classes/Domain/Model/Project.php
- packages/fgtclb/typo3-category-types/Classes/Domain/Model/CategoryType.php
Extbase does not call class constructor for domain models
when hydrating (thwating) from database, but calls custom
method `public function initializeObject(): void`, which
is a long-time known construct.
In older days that was only needed for `ObjectStorage`,
but became a harder requirement for other types domain
model properties and specially when custructor property
promotion is used.
Recommended design of Extbase Domain models boils down
to:
* Use native typed properties with default assignments as
long as it is possible.
* Keep `__construct()` clean and call `initializeObject()`.
* Use `initializeObject()` to ensure that all properties
are initialized, mainly when objects like `ObjectStorage`
needs to be set. Constructor and empty method are added
to all models with code comment to …
> [TASK] Streamline extbase domain model implementation

- packages/fgtclb/academic-persons-edit/Configuration/TCA/Overrides/fe_users.php
- packages/fgtclb/academic-persons-sync/Configuration/TCA/Overrides/fe_users.php
TYPO3 v12 deprecated TCA type=select items list array
items automigrating them to associative arrays while
triggering a `E_USER_DEPRECATED` notice in these cases.
`academic_persons_edit` and `academic_persons_sync`
register custom `tx_extbase_type` items using list
array style and hitting TCA automigration.
This change adopts the new associative item style for
regisered items.
[1] https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Deprecation-99739-IndexedArrayKeysForTCAItems.html
> [TASK] Mitigate TCA automigration for select items

- .github/workflows/publish.yml
- .gitignore
Each extension contains a dedicated publish GitHub workflow to
create an TER artifact and upload it to TER and add it within
each extension split repository created GitHub release.
This change introduces a publish workflow similar to that used
for each extension, except that it only creates GitHub release
and attaches TER upload packages of all extensions not process
any TER (TYPO3 Extension Repository) uploads.
Acts as a central place to have extension releases in a more
communicative way and ALL extension upload archives in one
place.
Using the GitHub commandline tool `gh` helps to download all
of them in one go when required, for example with:
```shell
mkdir -p extensions-2.0.1 \
&& gh release download 2.0.1 \
--repo fgtclb/academic-extensions \
--pattern '*_2.0.1.zip' …
```
> [TASK] Create release on monorepo with all extension archives

- packages/fgtclb/academic-bite-jobs/Configuration/FlexForms/Core13/AcademicBiteJobsList.xml
With TYPO3 v12 quite some tca stuff has been deprecated and
automigrated to new structures and adopted in TYPO3 v13 for
flexform the same way.
Some issues has been already addressed working on v12/v13
dual version support and fixed with core specific flexform
definition files.
Introducing new category type handling with #56 also changed
some flexforms, but sadly introduced depcreated `type=input`
with `eval=int` for a new option not covered by functional
tests and therefore was not detected earlier. [1]
This change migrates for TYPO3 v13 flexform the field directly
to the new `TCA type=number`. [2]
[1] https://github.com/fgtclb/academic-extensions/pull/56
[2] https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-97193-NewTCATypeNumber.html
> [TASK] Mitigate v13 flexform TCA migration

- packages/fgtclb/academic-projects/Classes/Upgrades/PluginUpgradeWizard.php
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/Fixtures/DataSets/onlyProjectListSingle_deletedButNotHidden.csv
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/Fixtures/DataSets/onlyProjectListSingle_notDeletedButHidden.csv
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/Fixtures/DataSets/onlyProjectListSingle_notDeletedOrHidden.csv
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/Fixtures/DataSets/onlyProjectList_deletedButNotHidden.csv
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/Fixtures/DataSets/onlyProjectList_notDeletedButHidden.csv
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/Fixtures/DataSets/onlyProjectList_notDeletedOrHidden.csv
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyProjectListSingle_deletedButNotHidden.csv
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyProjectListSingle_notDeletedButHidden.csv
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyProjectListSingle_notDeletedOrHidden.csv
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyProjectList_deletedButNotHidden.csv
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyProjectList_notDeletedButHidden.csv
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyProjectList_notDeletedOrHidden.csv
- packages/fgtclb/academic-projects/Tests/Functional/Upgrades/PluginUpgradeWizardTest.php
This change streamlines the `list_type` to `CType` upgrade
wizard of `academic-projects` to a modern and more explicit
implementation. This includes:
* Using constructor injection for `ConnectionPool`.
* Use QueryBuilder to update records in the database.
* Use QueryBuilder to check if update is neccessary
instead of hardcoded `true`.
* Adding tests for upgrade wizard to ensure working
state.
> [TASK] Streamline CType Upgrade wizard of `academic-projects`

- packages/fgtclb/academic-jobs/Classes/Upgrades/PluginUpgradeWizard.php
- packages/fgtclb/academic-jobs/Configuration/Icons.php
- packages/fgtclb/academic-jobs/Configuration/TCA/Overrides/tt_content.php
- packages/fgtclb/academic-jobs/Configuration/TSConfig/page.tsconfig
- packages/fgtclb/academic-jobs/Configuration/page.tsconfig
- packages/fgtclb/academic-jobs/Resources/Private/Language/de.locallang_be.xlf
- packages/fgtclb/academic-jobs/Resources/Private/Language/locallang_be.xlf
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/DataSets/onlyDetail_deletedButNotHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/DataSets/onlyDetail_notDeletedButHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/DataSets/onlyDetail_notDeletedOrHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/DataSets/onlyList_deletedButNotHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/DataSets/onlyList_notDeletedButHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/DataSets/onlyList_notDeletedOrHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/DataSets/onlyNewJobForm_deletedButNotHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/DataSets/onlyNewJobForm_notDeletedButHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/DataSets/onlyNewJobForm_notDeletedOrHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyDetail_deletedButNotHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyDetail_notDeletedButHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyDetail_notDeletedOrHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyList_deletedButNotHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyList_notDeletedButHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyList_notDeletedOrHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyNewJobForm_deletedButNotHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyNewJobForm_notDeletedButHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/Fixtures/Upgraded/onlyNewJobForm_notDeletedOrHidden.csv
- packages/fgtclb/academic-jobs/Tests/Functional/Upgrades/PluginUpgradeWizardTest.php
- packages/fgtclb/academic-jobs/UPGRADE.md
- packages/fgtclb/academic-jobs/ext_emconf.php
- packages/fgtclb/academic-jobs/ext_localconf.php
For a long time TYPO3 provided the sub-type feature
soley for the `tt_content` table and the core team
had to maintain a bag of painfull special cases in
the codebase without real benefit.
Right from the start it was possible to register
extbase plugins directly as `CType` instead of
the mostly used `list_type` sub-type registration.
Since TYPO3 v13 the list_type sub-type feature is
deprecated and is removed in v14, making the life
of the core team a bit easier. With the deprecation,
a migration upgrade wizard helper is provided, which
extension authors to add migrations in an easy step.
This extension needs to support TYPO3 v12 and v13
and a custom upgrade wizard is provided to process
the migration for 2.x.x directly on all suitable
TYPO3 versions.
Included in this change:
* `list_type` …
> [!!!][TASK] Migrate `academic_jobs` plugins to `CType`

- packages/fgtclb/academic-bite-jobs/ext_emconf.php
- packages/fgtclb/academic-contact4pages/composer.json
- packages/fgtclb/academic-contact4pages/ext_emconf.php
- packages/fgtclb/academic-jobs/ext_emconf.php
- packages/fgtclb/academic-partners/composer.json
- packages/fgtclb/academic-partners/ext_emconf.php
- packages/fgtclb/academic-persons-edit/composer.json
- packages/fgtclb/academic-persons-edit/ext_emconf.php
- packages/fgtclb/academic-persons-sync/composer.json
- packages/fgtclb/academic-persons-sync/ext_emconf.php
- packages/fgtclb/academic-persons/ext_emconf.php
- packages/fgtclb/academic-programs/composer.json
- packages/fgtclb/academic-programs/ext_emconf.php
- packages/fgtclb/academic-projects/composer.json
- packages/fgtclb/academic-projects/ext_emconf.php
- packages/fgtclb/typo3-category-types/ext_emconf.php
This change aligns basic information in `composer.json`
and `ext_emconf.php` files of all extensions to provide
the same setup and avoid the feeling of chaos.
That includes:
* Avoid developer names and email adresses as part of author
information in both aforementioned files in all extensions.
* Use `FGTCLB` als company, author and support information in
both aforementioned files over all extensions.
* Ensure having author/support information in the top of all
extension `composer.json` files.
* Having `ext_emconf.php` array keys sorted alphabetically to
provide the same ordering across all extensions and giving
a more clean and precise feeling across extensions.
* Prefix all extension titles in `ext_emconf.php` files with
`'FGTCLB: <title>'` to provide a aligned feeling across all …
> [TASK] Align information across all academic extensions

- README.md
Due to copy&paste errors creating the extension split
repository overview within the root `README.md` file,
it may be confusing.
This change mention the correct names now.
> [DOCS] Mention correct split repository names in `README.md`

- ddev-instances/core-12/composer.json
- ddev-instances/core-13/composer.json
Local development instances for supported TYPO3 Core versions
are basically available in `ddev-instances/core-*` albeit not
having currently a generated dataset available.
However, to prepare further towards a automatically startup,
generating a default dataset for the ddev instances, the one
or other preparation is required and in the making.
With this change more packages are added as composer dependencies
for the ddev instances acting as further preparations.
```shell
BIN_COMPOSER="$( which composer )" \
&& ${BIN_COMPOSER} require \
-d ddev-instances/core-12 \
--no-update \
"bk2k/bootstrap-package":"^15.0@dev" \
&& ${BIN_COMPOSER} require \
-d ddev-instances/core-13 \
--no-update \
"bk2k/bootstrap-package":"^15.0@dev"
```
> [TASK] Further prepare ddev instances

- packages/fgtclb/academic-projects/Documentation/Index.rst
This change adds some line breaks in the documentation
to avoid excessive line lengths. But to be fully honest,
the main goal is trying to get a initial documentation
rendering happen on intercept.
> [DOCS] Add some line breaks in documentation

- packages/fgtclb/academic-partners/Configuration/TCA/tx_academicpartners_domain_model_role.php
Using copy&paste from other extension is often a source for human
errors and can slip through reviews, special when part of bigger
mono-repository and old/new version aggregation.
`academic-partners` provides `tx_academicpartners_domain_model_role`
as TCA managed table and configured `type=0` showitems for it, but
used a non-existing table column.
This change replaces the wrong column name `contacts` with the
correct `partnerships` column name to tell TYPO3 to display it.
Cherry-picked from https://github.com/fgtclb/academic-extensions/pull/120
> [BUGFIX] Configure correct type=0 showitem field for TCA table

- packages/fgtclb/academic-partners/Classes/Domain/Model/Partner.php
As the "abstract" property of the "Partner" model is protected and therefore can not be accessed without an appropriate public `get` function to return the property value, accessing it in templates is not
possible.
Thus a `get` function for the "abstract" property has been added to allow usage in e.g. the list view.
> [TASK] Allow access on protected property

- Build/phpstan/Core12/phpstan-baseline.neon
- Build/phpstan/Core13/phpstan-baseline.neon
- packages/fgtclb/academic-persons/Classes/Event/ModifyDetailProfileEvent.php
The `ModifyDetailProfileEvent` contains a property and
provides a getter for the view object, which has been
based on an extbase related ViewInterface and changed
through multiple TYPO3 and standalone Fluid versions.
This change uses the correct fluid and TYPO3 interfaces
now directly as native types compatible with TYPO3 v12
and v13 and remobes the deprecated v11 extbase interface
as a cleanup due to dropped TYPO3 v11 support and solves
the todo comments in the aforementioned class.
That allows us to remove phpstan ignorePatters from the
baselines and further improving the code quality.
```shell
Build/Scripts/runTests.sh -p 8.1 -t 12 -s composerUpdate \
&& Build/Scripts/runTests.sh -p 8.1 -t 12 -s cgl \
&& Build/Scripts/runTests.sh -p 8.1 -t 12 -s phpstanGenerateBaseline …
```
> [TASK] Adjust types in `ModifyDetailProfileEvent`

- packages/fgtclb/academic-persons/Classes/Profile/AbstractProfileFactory.php
- packages/fgtclb/academic-persons/UPGRADE.md
Using constructor dependency injection in abstract classes
defines the constructor as API, which should be avoided by
using the inject-method approach and allows to implement
classes using constructor DI without the requirement to deal
and align with parent (abstract) class constructor and passing
it down.
`AbstractProfileFactory` used constructor DI and therefore
violated the above described design pattern.
This change replaces the constructor injection with inject
methods freeing the constructor, which is a breaking change.
The next minor version already contains a couple of breaking
changes and will be communicated as such, which allows us
this change now and mitigate breaking changes related to DI
in the abstract class for the future.
Additionally, the …
> [!!!][TASK] Avoid constructor DI in `AbstractProfileFactory`

- packages/fgtclb/academic-persons/Classes/PageTitle/ProfileTitleProvider.php
- packages/fgtclb/academic-persons/Tests/Functional/PageTitle/ProfileTitleProviderTest.php
- packages/fgtclb/academic-persons/UPGRADE.md
To allow configurable person detail view page titles, a placeholder
based format option has been introduced for the added and dispatch
of a (internal) PSR14 event for each resolved placeholder, which
should help projects to implement custom placeholder replacements.
It just turned out, that the used regular expression to split the
placeholder was to restrictive and preventing to implement custom
event listener to make localization identifier like placeholders
to resolve to translated values, for example placeholders like:
```
%%LLL:EXT:myext/Resources/Private/Languages/locallang.db:identifier%%
```
That discovery made it clear, that the pattern needs to be envolved
to allow more customization and not blocking project or extension
developers, which boils down to:
* Allow space character ` …
> [BUGFIX] Allow more characters for `pageTitleFormat` placeholders

- packages/fgtclb/academic-jobs/Configuration/TypoScript/setup.typoscript
- packages/fgtclb/academic-partners/Configuration/TypoScript/Content/ContentLoad.typoscript
- packages/fgtclb/academic-partners/Configuration/TypoScript/Page/AcademicPartners.typoscript
- packages/fgtclb/academic-programs/Configuration/TypoScript/Content/ContentLoad.typoscript
- packages/fgtclb/academic-programs/Configuration/TypoScript/Page/AcademicPrograms.typoscript
- packages/fgtclb/academic-projects/Configuration/TypoScript/Content/ContentLoad.typoscript
- packages/fgtclb/academic-projects/Configuration/TypoScript/Page/AcademicProjects.typoscript
TypoScript is the frontend rendering configuration tool, but some
exension tend to use extbase stuff or similar in CLI context where
no valid web request exists OR try to load TypoScript for pages,
not providing full context information in globals.
If TypoScript is not written in a safe way for context missuses,
that may crash or lead at least to spamming error log files.
For example following TypoScript condition:
```
[traverse(page, "doktype") == 30]
[END]
```
is considered unsafe for above-mentioned, unsafe context setups.
To mitigate this, this change adds addition stuff to TypoScript
to mitigate errors (crashes), even if that means that this may
be lead to unexpected configurations, which should be safe in
the most cases.
Some todo comments added on side-findings.
> [BUGFIX] Harden TypoScript for non-web request context usage

- Build/phpstan/Core12/phpstan-baseline.neon
- Build/phpstan/Core13/phpstan-baseline.neon
- packages/fgtclb/academic-persons/Classes/Event/ModifyListProfilesEvent.php
The `ModifyListProfilesEvent` contains a property and
provides a getter for the view object, which has been
based on an extbase related ViewInterface and changed
through multiple TYPO3 and standalone Fluid versions.
This change uses the correct fluid and TYPO3 interfaces
now directly as native types compatible with TYPO3 v12
and v13 and removes the deprecated v11 extbase interface
as a cleanup due to dropped TYPO3 v11 support and solves
the todo comments in the aforementioned class.
That allows us to remove phpstan ignorePatters from the
baselines and further improving the code quality.
In general this follows a similar change made with [1].
```shell
Build/Scripts/runTests.sh -p 8.1 -t 12 -s composerUpdate \
&& Build/Scripts/runTests.sh -p 8.1 -t 12 -s cgl \
&& …
```
> [TASK] Adjust types in `ModifyListProfilesEvent`

- packages/fgtclb/academic-persons/Resources/Private/Partials/Profile/Contract/Field.html
- packages/fgtclb/academic-persons/Resources/Private/Partials/Profile/Contract/Item.html
As the `<f:trim />` ViewHelper did not work as expected and
did not remove the entire string. Instead each character in
it from the beginning of the target string was replaced.
To achieve the wanted behaviour the `<f:split />` ViewHelper
is the more suiting canditate for the job and is now used to
replace the `<f:trim />` ViewHelper.
`<f:trim />` usage:
```
'contracts.room' => 'm'
'contracts.orginisationalUnit' => 'rginisationalUnit'
```
`<f:split />` usage:
```
'contracts.room' => {0: 'contracts', 1: 'room'}
'contracts.orginisationalUnit' =>  {0: 'contracts', 1: 'orginisationalUnit'}
```
This way we can guarantee to have the string split at the
correct character and access the field name, to pass down
to the partial, more reliably.
`<f:split />` ViewHelper has been introduced in …
> [BUGFIX] Use `<f:split />` to split `showFields` to gain expected result

- .github/workflows/core-12.yml
- .github/workflows/core-13.yml
- Build/Scripts/runTests.sh
First alpha version of PHP 8.5 has been released and
a core-testing image for this version build based on
upstream PHP base image.
This change allows now to use `PHP 8.5` in the known
dispatcher `Build/Scripts/runTests.sh` as option and
enables testing in automatic GitHub actions for the
new version directly.
> [TASK] Add PHP 8.5 to testing matrix

- packages/fgtclb/typo3-category-types/Classes/ServiceProvider.php
`EXT:cagtegory_types` provides a yaml based configuration file to
register category types along with icons in one place and ensures
to register categorys at all related places, for example the TCA
configuration for `sys_category` (type feature) along with icon
classes. It uses registered icon identifiers, which are registered
by the extension `ServiceProvider` during DI build time.
For registration of icons the `IconRegistry::detectIconProvider()`
method has been used to decide which iconProvider to use looking
for `.svg` in provided icon file.
However, the implementation hands over the icon identifier and
not the icon file and the detection returns always the default
`BitmapIconProvider` even for  `SVG` files.
This change passes now the icon to the detect method to get the
correct …
> [BUGFIX] Use `SvgIconProvider` for svg category icons

- packages/fgtclb/academic-persons/Classes/Controller/ProfileController.php
- packages/fgtclb/academic-persons/Classes/Event/ModifyDetailProfileEvent.php
- packages/fgtclb/academic-persons/Classes/Event/ModifySelectedContractsEvent.php
- packages/fgtclb/academic-persons/Classes/Event/ModifySelectedProfilesEvent.php
- packages/fgtclb/academic-persons/UPGRADE.md
Starting with `2.x` and moving to `TYPO3 v12 & v13` compatibility, two new
plugins has been introduced:
* academicpersons_selectedprofiles
* academicpersons_selectedcontracts
where the `academicpersons_selectedprofiles` was meant as a standalone controllable
plugin in projects as replacedment for the subfeature to select profiles and the
`academicpersons_list` and `academicpersons_listanddetail`, and some code has been
copy & pasted during the implementation of the new actions for the new plugins.
Sadly, dispatching the same `ModifyListProfilesEvent` has also copied over making
it hard in projects or addon extension to distingush for which plugin the event
has been dispatched.
With recently introduced `PluginControllerActionContextInterface` added to the
dispatched event eventlistiner …
> [!!!][FEATURE] Introduce new events for `SelectedProfiles` and `SelectedContracts`

- packages/fgtclb/academic-persons/Classes/PageTitle/ProfileTitleProvider.php
- packages/fgtclb/academic-persons/Resources/Private/Language/locallang.xlf
- packages/fgtclb/academic-persons/Tests/Functional/AbstractAcademicPersonsTestCase.php
- packages/fgtclb/academic-persons/Tests/Functional/Fixtures/Extensions/test_language_files/Resources/Private/Language/de.locallang.xlf
- packages/fgtclb/academic-persons/Tests/Functional/Fixtures/Extensions/test_language_files/Resources/Private/Language/locallang.xlf
- packages/fgtclb/academic-persons/Tests/Functional/Fixtures/Extensions/test_language_files/composer.json
- packages/fgtclb/academic-persons/Tests/Functional/Fixtures/Extensions/test_language_files/ext_emconf.php
- packages/fgtclb/academic-persons/Tests/Functional/PageTitle/ProfileTitleProviderTest.php
- packages/fgtclb/academic-persons/UPGRADE.md
It's a valid use-case to use a pageTitleFormat for the person
profile detail page view as HTML page title including localized
text as placeholders and could be implemented using the PSR-14
event `ModifyProfileTitlePlaceholderReplacementEvent` dispatched
in the `ProfileTitleProvider`.
Localization is a generic feature and it's most likely that it's
use-full for a broader audience this change adds now support for
localization placeholder in the format:
```
%%LLL:EXT:<extension-key>/Resources/.../locallang.xlf:identifier%%
```
Note that no context fallback detection is made like within fluid
templates or extbase context areas and a valid relative path for
the default language file within a extension needs to be provided.
Functional tests are added to cover the new feature basically and …
> [FEATURE] Introduce localized pageTitleFormat placeholder (`LLL:EXT:`)

- packages/fgtclb/academic-persons/Configuration/TypoScript/Default/setup.typoscript
- packages/fgtclb/academic-persons/Configuration/TypoScript/Shared/allow_typoscript_override_empty_flexform_settings.typoscript
TYPO3 provides the ability to define settings for plugin in TypoScript and
also as FlexForm (`pi_flexform`) settings. Extbase `ConfigurationManager`
merged settings from both sources having FlexForm options with the higher
priority, which means that empty FlexForm settings overrides TypoScript
settings.
In many cases it is more suitable that TypoScript settings should override
FlexForm settings when not set (empty) to allow instance wide configuration
and placing plugins in `tt_content` without setting the values on each of
these places. In the past, Extension authors needed to define these cases
and implement that manually for each plugin/action again and again, which
was a pain in the ass.
Since TYPO3 v12.3 the new option `ignoreFlexFormSettingsIfEmpty` [1] gives
the option to tell …
> [TASK] Allow TypoScript settings to override empty FlexForm settings

- packages/fgtclb/academic-persons-edit/Classes/Controller/ContractController.php
- packages/fgtclb/academic-persons-edit/Classes/Controller/EmailAddressController.php
- packages/fgtclb/academic-persons-edit/Classes/Controller/PhoneNumberController.php
- packages/fgtclb/academic-persons-edit/Classes/Controller/PhysicalAddressController.php
- packages/fgtclb/academic-persons-edit/Classes/Controller/ProfileInformationController.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/Address.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/Contract.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/Email.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/PhoneNumber.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/ProfileInformation.php
- packages/fgtclb/academic-persons/Tests/Unit/Domain/Model/ContractTest.php
- packages/fgtclb/academic-persons/Tests/Unit/Domain/Model/EmailTest.php
- packages/fgtclb/academic-persons/Tests/Unit/Domain/Model/PhoneNumberTest.php
- packages/fgtclb/academic-persons/Tests/Unit/Domain/Model/ProfileInformationTest.php
Extbase has quite some requirements related to model properties
and setter/getter methods, special with newer PHP versions and
native types.
That also boils down to the two ways models may be created:
* using new (in manual code) and thus this constructor
* hydrating from the database not calling the constructor
Extbase in general maps data directly to the properies for all
data retrieved from the database, which means for relations
that it will be left out and requires that relations are declared
as nullabe and getter/setter can deal with it.
All of these things has not been respected and are now streamlined
to avoid issues in different flavours and places.
> [BUGFIX] Streamline extbase model properties and getters

- packages/fgtclb/academic-persons/Classes/Backend/Form/ProfileShowFieldsItemProcFunc.php
Value item array for TCA select fields used integer keys for a long
time with specific meaning for each position [1], for example:
```php
[
[
0 => 'item label',
1 => 'item value',
2 => 'item icon identifier',
3 => 'group identifier',
],
],
```
This behaviour has changed in TYPO3 v12 in favour of associative keys,
making it easier to read and understand for developers with the side
effect that it is not that fragile when ordering puzzles arround [2],
for example:
```php
[
[
'label' => 'item label',
'value' => 'item value',
'icon' => 'item icon identifier',
'group' => 'group identifier',
],
],
```
To provide dual TYPO3 core version support and avoid automatic
TCA migration and hitting `E_USER_DEPRECATED` messages due to
the deprecation, a key-to-use switch had been added with commit …
> [BUGFIX] Use correct key for select item icon value

- packages/fgtclb/academic-contact4pages/ext_emconf.php
The TYPO3 Extension Repository fails when a extension `ext_emconf.php`
contains the PHP `declare(strict_types=1);` and cannot properly decode
the extension details to handle the upload.
This change removes that statement to make `ext_emconf.php` valid for
an automatic upload to TER using the `typo3/tailor` tool.
> [BUGFIX] Remove `declare(strict_types=1);` in `ext_emconf.php`

- packages/fgtclb/academic-bite-jobs/Configuration/FlexForms/Core13/AcademicBiteJobsList.xml
- packages/fgtclb/academic-bite-jobs/Configuration/Sets/AcademicBiteJobs/config.yaml
- packages/fgtclb/academic-bite-jobs/Configuration/Sets/AcademicBiteJobs/constants.typoscript
- packages/fgtclb/academic-bite-jobs/Configuration/Sets/AcademicBiteJobs/page.tsconfig
- packages/fgtclb/academic-bite-jobs/Configuration/Sets/AcademicBiteJobs/setup.typoscript
- packages/fgtclb/academic-bite-jobs/Configuration/TCA/Overrides/tt_content.php
- packages/fgtclb/academic-bite-jobs/Configuration/TsConfig/Wizards/NewContentElement.tsconfig
- packages/fgtclb/academic-bite-jobs/Resources/Private/Language/de.locallang_be.xlf
- packages/fgtclb/academic-bite-jobs/Resources/Private/Language/locallang_be.xlf
* **[TASK] Introduce site set based configuration**
According to site sets in v13 introduced lately the files and folder
structure is changed for working in both v12 and v13 systems. This
contains mainly the creation of files which load the former available
TypoScript files.
Additionally the tsConfig for the New Content Element Wizard has been
added.
[1] https://docs.typo3.org/m/typo3/reference-coreapi/13.4/en-us/ApiOverview/SiteHandling/SiteSets.html
* **[TASK] Overhaul of loading of plugin flex form**
The flexform based configuration tab for the plugin was missing in v13.
This was fixed according to the standard way working throughout all of
the `academic_*` extensions so far.
This contains:
* Fixed registration error of the flexform file for the plugin content 
element. 
* Fixed …
> [TASK] Improve TYPO3 v13 for `EXT:academic-bite-jobs` 

- packages/fgtclb/academic-base/Configuration/Sets/AcademicBaseCTypeGroup/page.tsconfig
This commit resolves a typo in the `page.tsconfig` file for the Site Set configuration for TYPO3 v13. The import path for the `academic_base` extension was incorrectly spelled as `academic_`.
This correction ensures that the TSconfig files are properly loaded from the correct extension directory.
> [TASK] Fix typo in Site Set TSconfig import path

- packages/fgtclb/academic-base/composer.json
This change sets the missing branch alias for the
`EXT:academic_base` to mitigate issues using the
development version in projects.
```shell
BIN_COMPOSER="$( which composer2-81 )" \
&& ${BIN_COMPOSER} config \
-d packages/fgtclb/academic-base \
"extra"."branch-alias"."dev-main" "2.0.x-dev"
```
> [TASK] Set missing branch alias for `EXT:academic_base`

- Build/phpstan/Core13/phpstan-baseline.neon
- packages/fgtclb/academic-base/Classes/Extbase/Property/TypeConverter/FileUploadConverter.php
- packages/fgtclb/academic-base/Configuration/Services.yaml
- packages/fgtclb/academic-base/Resources/Private/Language/de.locallang.xlf
- packages/fgtclb/academic-base/Resources/Private/Language/locallang.xlf
- packages/fgtclb/academic-base/Tests/Functional/AbstractAcademicBaseTestCase.php
- packages/fgtclb/academic-base/Tests/Functional/Extbase/Property/TypeConverter/FileUploadConverterTest.php
- packages/fgtclb/academic-base/Tests/Functional/ExtensionLoadedTest.php
Since ages projects and extensions needs to implement a custom
extbase TypeConvert to support file upload in extbase related
forms to be attached as file references to extbase models or
DTO's, enforcing to make adoptions for TYPO3 core changes over
and over again.
With TYPO3 v13 [1] a new system has been introduced to provide
that feature directly, which we cannot use due to the support
of TYPO3 v12 and a backport within a extension is not reasonable
based on the required patches, xclasses and similiar deep within
extbase internal API and class constructs.
The academic extensions implemeted already such a custom type
converter and needs it in more places and is the reason why it
is now implemented in `EXT:academic_base` to have a shared and
reusable implementation across all academic …
> [TASK] Introduce centralized `FileUploadConverter` implementation

- packages/fgtclb/academic-bite-jobs/Classes/Controller/BiteJobsController.php
Sometimes there is the need for rendering informations contained in the content element which delivers the list plugin. This could be headers or layout informations just to name two of them. For ease of use we inject those information into the view variables.
This gives an easy way for rendering those stuff, e.g:
```
<f:render partial="Header/All" arguments="{data}" />
```
> [TASK] Enrich template variables with content element data

- packages/fgtclb/academic-persons-edit/Classes/Controller/ContractController.php
- packages/fgtclb/academic-persons-edit/Classes/Controller/EmailAddressController.php
- packages/fgtclb/academic-persons-edit/Classes/Controller/PhoneNumberController.php
- packages/fgtclb/academic-persons-edit/Classes/Controller/PhysicalAddressController.php
- packages/fgtclb/academic-persons-edit/Classes/Controller/ProfileInformationController.php
- packages/fgtclb/academic-persons-edit/UPGRADE.md
The `newAction()` of the `EXT:academic_persons_edit` controllers only
displays the initial form for create a new entity submitting data
submission to the `createAction()` [POST] and never handles the form
again. Following that, there is no need to have form data as optional
argument for the `newAction()` and beside that this would allow to
prefill data used for the form using link manipulations as the action
is a GET action, which we do not want to work.
Not verified if having the form object as nullable for action in place
has been required in earlier extbase days, but today that is absolutely
not the case and **could** only be uses to prefill form data calling
that action with corresponding get arguments, which can be considered
dangerous and needs to be omitted in the first place.
In …
> [!!!][TASK] ACE-33: Remove obsolete form DTO from controller `newAction()`

- packages/fgtclb/academic-persons-edit/Classes/Domain/Factory/EmailFactory.php
`EmailFactory->updateFromFormData()` has a mismatch in variable
name usage between sub method return values and method argument
passing and thus breaking correct model update based on the form
data transfer object.
This change uses the correct variable names now to repair the
update of the domain model object and set form data correctly.
> [BUGFIX] ACE-33: Use correct variable names in `EmailFactory->updateFromFormData()`

- packages/fgtclb/academic-base/Classes/Controller/GetSelectItemsForTcaManagedTableFieldMethodTrait.php
- packages/fgtclb/academic-base/Classes/Event/ModifyTcaSelectFieldItemsEvent.php
- packages/fgtclb/academic-jobs/Classes/Backend/FormEngine/EmploymentTypeItems.php
- packages/fgtclb/academic-jobs/Classes/Backend/FormEngine/TypeItems.php
- packages/fgtclb/academic-jobs/Classes/Controller/JobController.php
- packages/fgtclb/academic-jobs/Tests/Functional/Backend/FormEngine/EmploymentTypeItemsTest.php
- packages/fgtclb/academic-jobs/Tests/Functional/Backend/FormEngine/TypeItemsTest.php
- packages/fgtclb/academic-jobs/UPGRADE.md
`EXT:academic_jobs` provides following `itemsProcFunc` handler:
* `EmploymentTypeItems`
* `TypeItems`
which defines default items for fields (TCA or flexfom) using
these `itemsProcFunc` handlers. These are used in the backend
within the `FormEngine` and additionally dispatched manually
in the `JobController` to retrieve the available select items.
Previously, it was required to add them either directly not
having an influence to the ordering OR to implement a custom
`itemsProcFunc` replacing the shipped version and both ways
are not really nice or testable.
To provide an easier way for projects to modify the available
select items, the handler now dispatches the newly introduced
shared event `ModifyTcaSelectFieldItemsEvent` added to the    
`EXT:academic_base` extension to reuse the same …
> [FEATURE] Dispatch PSR-14 `ModifyTcaSelectFieldItemsEvent` in `itemsProcFunc`

- packages/fgtclb/academic-persons-edit/Classes/EventListener/SyncChangesToTranslations.php
- packages/fgtclb/academic-persons-edit/Tests/Functional/EventListener/SyncChangesToTranslationsTest.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/Dto/Syncronizer/SyncronizerContext.php
- packages/fgtclb/academic-persons/Classes/Service/RecordSyncronizer.php
- packages/fgtclb/academic-persons/Classes/Service/RecordSyncronizerInterface.php
- packages/fgtclb/academic-persons/Tests/Functional/Service/RecordSyncronizerTest.php
`EXT:academic_persons_edit` implements a PSR-14 event for the
`AfterProfileUpdateEvent` event dispatched in the controller,
with the goal to syncronize profile and relations for languages
configured in the extension configuration.
The internal code within the event listener to handle the sync
for profile and relation records has a couple of issues, which
needs to be investigated, fixed and tested.
Following best practice, event listeners should be glue code
like for example controllers and using services to accomplish
complexer tasks, which is not done here.
This change extracts the handling code from the event listener
of `EXT:academic_persons_edit` into a new services provided by
`EXT:academic_persons` now with a streamlined outer surface,
moving the internal code simply to the new …
> [TASK] Extract record translation into dedicated `RecordSyncronizationService`

- packages/fgtclb/academic-persons-edit/Classes/EventListener/SyncChangesToTranslations.php
- packages/fgtclb/academic-persons-edit/Tests/Functional/EventListener/SyncChangesToTranslationsTest.php
- packages/fgtclb/academic-persons/Classes/Domain/Model/Dto/Syncronizer/SynchronizerContext.php
- packages/fgtclb/academic-persons/Classes/Service/RecordSynchronizer.php
- packages/fgtclb/academic-persons/Classes/Service/RecordSynchronizerInterface.php
- packages/fgtclb/academic-persons/Tests/Functional/Service/RecordSyncronizerTest.php
Translation synchronization related code has been extracted
into dedicated services recently, sadly the type naming the
classes and method(s) has been overseen.
This change renames classes and methods to have the correct
spelling `synchronization` instead of `syncronization` and
similar. Mind the missing `h`.
> [TASK] ACE-104: Fix typo in synchronizer classes

- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/Profile/Properties/EmailAddress.html
Extbase comes with a lot of convention and magic in the
bagpack, which requires honest build up of things.
Automatic controller arguments mapping to DTO objects,
which are not extended from persisted extbase models,
has the requirement that the form identifier used in
fluid templates with `f:form.*` ViewHelpers needs to
match the `constructor argument name`.
This has been provided correctly fixing CRUD functions
of `EXT:academic_persons_edit`, but later the shipped
fluid templates has been reworked and not adopted in
the correct way.
This change uses the correct identifier for the email
adress DTO `email` argument in the property template,
which allows persistance of email addresses again.
> [BUGFIX] Use correct object property name for `EmailAddressFormData`

- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/Profile/Forms/Checkbox.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/Profile/Forms/DateTime.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/Profile/Forms/Select.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/Profile/Forms/Textarea.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/Profile/Forms/Textfield.html
Using inline ViewHelper notation breaks IDE support to display
ViewHelper arguments help with available (generated) XSD files
and prevents autocompletion.
This change reverts switching to inline notation for ensuring
validations information is set correctly and keep IDE support
available.
Using inline notation for ViewHelpers **should** only be used
if there is now way around, for example within a attribute of
a HTML tag and is considered best-practice by TYPO3 Core and
Fluid Team maintainers. Even in case of attributes assigning
the ViewHelper result into a variable before usage and using
the variable instead makes templates more readable and keeps
IDE features working.
Litterally, `f:translate` is used with inline notation in all
places, which makes it harde to find typo's in wrong …
> [TASK] Avoid inline syntax for validationEnsure ViewHelper usage

- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/Profile/Properties/EmailAddress.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/Profile/Properties/PhoneNumber.html
- packages/fgtclb/academic-persons-edit/Resources/Private/Partials/Profile/Properties/PhysicalAddress.html
Because the passed variables were missing the select options
those were always empty. Passing them down to the select
partial now renders the options.
> [TASK] Pass type options to fluid templates rendering the form fields

- packages/fgtclb/academic-persons-edit/Resources/Private/Templates/Contract/Show.html
Because the location field no longer is an input but a select
field, the selected option needs to be accessed differently when
showing the contract values. Therefore the HTML has been
adjusted to correctly render the name of the location.
> [TASK] Use title field to display location name
